# @url=https://message.credot.ml
@url=http://localhost:3000

################################
POST {{url}}/api/message
Content-Type: application/json

{
    "service":"test",
    "phone":"0921771865",
    "message":"testmessage",
    "checksum":"04895a1690b3342a30503e42fc47cf275c4279e4679af3562c10f4b312a537ea"
}

##########
GET {{url}}/api/mtk

#########
GET {{url}}/api/message?service=test&durationStart=2021-07-31T16:00:00.000Z&durationEnd=2021-08-31T16:00:00.000Z&checksum=0b72dccd2105d9db50c833cec8e562c98f3c46466675803d2117f5a7146a474e&limit=2&offset=2