# @url=https://message.credot.ml
@url=http://localhost:3000

################################
POST {{url}}/api/mail
Content-Type: application/json

{
    "service":"test",
    "subject":"testsub",
    "html":"<ul><li>list1</li><li>list2</li><li>list3</li></ul>",
    "target":["skynocover@Gmail.com"],
    "datetime":"2021-08-31T16:51:19.808Z",
    "checksum":"3800979489f36f5003a17991f393b971ba95c11cffb0408b773789f4611e2c54"
}

##########
GET {{url}}/api/mtk

#########
GET {{url}}/api/message?service=test&durationStart=2021-07-31T16:00:00.000Z&durationEnd=2021-08-31T16:00:00.000Z&checksum=0b72dccd2105d9db50c833cec8e562c98f3c46466675803d2117f5a7146a474e&limit=2&offset=2