@url=https://mail-server.vercel.app
# @url=http://localhost:3000

################################
POST {{url}}/api/mail
Content-Type: application/json

{
    "service":"test",
    "subject":"testsub",
    "html":"<ul><li>list1</li><li>list2</li><li>list3</li></ul>",
    "target":["skynocover@Gmail.com"],
    "datetime":"2021-08-31T16:51:19.808Z",
    "checksum":"3800979489f36f5003a17991f393b971ba95c11cffb0408b773789f4611e2c54"
}

#########
GET {{url}}/api/mail?service=test&durationStart=2021-08-01T16:00:00.000Z&durationEnd=2021-09-30T16:00:00.000Z&checksum=60e04ba6033ffdbb5352e4ca4fbb0b4c495908f95a0c62d10dc2bebfda04425e